name: gerryr-ytdlp # 'snapcraft register gerryr-ytdlp'
title: gerryR ytdlp
base: core24
contact: https://www.gerryr.com
website: https://www.gerryr.com
version: '0.1'
summary: yt-dlp is a feature-rich command-line audio/video downloader
description: |
  yt-dlp is a feature-rich command-line audio/video downloader with support for thousands of sites.
  The project is a fork of youtube-dl based on the now inactive youtube-dlc. https://github.com/yt-dlp/yt-dlp

  This snap is not endorsed by the yt-dlp project.

platforms:
  amd64:

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  gerryr-ytdlp:
    plugin: python
    source-type: git
    source: https://github.com/yt-dlp/yt-dlp
    stage-snaps:
      - ffmpeg-2404

apps:
  gerryr-ytdlp:
    command: bin/yt-dlp
    plugs:
      - home